### ISSUE TITLE
ffmpeg exited with code 1

### ISSUE THREAD

**Issue by mpirescarvalho** [ytb2mp3/youtube-mp3-downloader#67]
I'm getting errors on some videos that I can't figure out why or how to solve. I always get the error on some videos like ```2ky7V-jMcZI```

here's my code:

```
const YD = new YoutubeMp3Downloader({
      ffmpegPath: 'ffmpeg',
      outputPath: 'temp/audio',
      youtubeVideoQuality: 'highestaudio',
      queueParallelism: 1,
      progressTimeout: 2000,
      allowWebm: true,
    });

    YD.download('2ky7V-jMcZI', 'test.mp3');

    YD.on('finished', async (error, data) => {
      console.log(!error ? 'success' : error);
    });

    YD.on('error', error => console.log(error));
```

here's the output:

```
ffmpeg exited with code 1: Error initializing output stream 0:0 -- Error while opening encoder for output stream 
#0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

**Comment by ctoveloz** [comment]
I Have the same error with some id's
`ffmpeg exited with code 1: pipe:0: Invalid data found when processing input`

In [node-ytdl-core](https://github.com/fent/node-ytdl-core/issues/567) have the same error.

**Comment by mpirescarvalho** [comment]
I don't think that's the same error, but I've fixed mine. Check the PR #68

**Comment by ytb2mp3** [comment]
I added the assignment of a default audio bitrate in 1a72793e69b273a02d0355dc0487702193c1c573. I don't really think it's correct to use the video bitrate as audio bitrate like @ctoveloz suggested. New version `0.7.5` is about to be released

**Comment by ytb2mp3** [comment]
This is fixed in version `0.7.5`.

**Comment by DaliuSinger** [comment]
I am also getting the same error "ffmpeg exited with code 1: pipe:0: Invalid data found when processing input", on longer videos, something 15mins or longer, works ok on under 10mins long videos. So I assume, the issue is not fixed... Current version 0.7.10. I noticed that downloader over jumps 100% complete mark, not sure how to fix it.

**Comment by eladcandroid** [comment]
@DaliuSinger Did you find something?
